# Generated by Django 2.2.16 on 2020-09-23 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0002_penerimaan_organisasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penerimaan',
            name='entryer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entryer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='penerimaan',
            name='organisasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisasi', to='organization.Organization'),
        ),
    ]
