# Generated by Django 2.2.16 on 2020-09-23 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_author_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'authors'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'book'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='organization.Author'),
        ),
    ]
