# Generated by Django 2.2.16 on 2020-09-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wilayah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propinsi',
            name='kode',
            field=models.IntegerField(default=0),
        ),
    ]
