# Generated by Django 2.2.16 on 2020-09-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wilayah', '0002_propinsi_kode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propinsi',
            name='kode',
            field=models.IntegerField(),
        ),
    ]
