# Generated by Django 2.2.16 on 2020-09-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wilayah', '0004_kota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kota',
            name='kode',
            field=models.CharField(max_length=50),
        ),
    ]
