# Generated by Django 2.2.16 on 2020-09-20 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wilayah', '0005_auto_20200920_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Unselect this instead of deleting accounts.', verbose_name='active')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('kode', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=250)),
                ('kota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wilayah.Kota')),
                ('propinsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wilayah.Propinsi')),
            ],
            options={
                'verbose_name': 'Kecamatan',
            },
        ),
    ]
