# Generated by Django 2.2.16 on 2020-09-20 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengurus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jabatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Jabatan', verbose_name='jabatan'),
        ),
    ]
