# Generated by Django 2.2.16 on 2020-09-23 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20200923_0734'),
        ('pengurus', '0002_auto_20200920_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='menjabat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Organization', verbose_name='menjabat'),
        ),
    ]
